### ISSUE TITLE
problem when the datetimepicker has a value

### ISSUE THREAD

**Issue by maknaoui** [T00rk/bootstrap-material-datetimepicker#12]
i find a problem when the input have value="2015-06-08 11:50" , the date isn't selected.

**Comment by T00rk** [comment]
Sorry for the late.
I've tried it and I have the same issue.
I'm on it, but, for now you could set the object `currentDate` instead of html value. Maybe that could help you until I fix it.

**Comment by T00rk** [comment]
I think it's fixed. It took less time I thought.
Can you confirm it's ok ?
