### ISSUE TITLE
12H time format

### ISSUE THREAD

**Issue by VeeK727** [T00rk/bootstrap-material-datetimepicker#126]
Can you add an option to select and display the time in 12H format? So 21:00 would be 09:00 PM

**Comment by sadalsuud** [comment]
in the example on demo live, the last example is this seted.

**Comment by VeeK727** [comment]
Can you share the link you are referring to?

**Comment by sadalsuud** [comment]
[link live demo](http://t00rk.github.io/bootstrap-material-datetimepicker/)

**Comment by VeeK727** [comment]
That is the link i went to check but I don't see any example that shows `shortTime: true` setting. Am I missing something?

**Comment by sadalsuud** [comment]
Well... I see in the source code ... The important is set this:  shortTime: true when you are Initializing the component
for example: ```

$('#hora_inicio').bootstrapMaterialDatePicker({
    date: false,
    shortTime: true,   // look
    format: 'HH:mm',
    switchOnClick: true
});
```

**Comment by rohitsinghshan** [comment]
I wanna to show AM and PM in input ith time how I can show that

**Comment by usamamashkoor** [comment]
@rohitsinghshan did you find any solution...?

**Comment by Spider-ant** [comment]
Any solution to this?
