### ISSUE TITLE
Use date and time separately

### ISSUE THREAD

**Issue by Shehab-Eltawel** [T00rk/bootstrap-material-datetimepicker#14]
Can I use time picker separately ?

**Comment by T00rk** [comment]
No you can use just date or date and time

**Comment by T00rk** [comment]
I'm gonna fix this soon

**Comment by T00rk** [comment]
It's now possible to use time without date.
Just set `date : false` in your options. 
I hope you'll like it

**Comment by Shehab-Eltawel** [comment]
You just  did a big favor to every one in the community interested in Material Design.

Thanks a lot.
