### ISSUE TITLE
Make it responsive

### ISSUE THREAD

**Issue by magarcia** [T00rk/bootstrap-material-datetimepicker#15]
The modal is too big for a mobile device.

![screenshot_2015-06-18-23-43-28](https://cloud.githubusercontent.com/assets/651610/8243056/221e0d92-1614-11e5-8c79-81b6e3a257e6.png)

**Comment by T00rk** [comment]
Yes I know it and i'm fixing it

**Comment by nogdacosta** [comment]
I've edited the first line from the css.
instead of "width: 400px", you use "max-width".

.dtp .modal-dialog{max-width: 400px;}

also, in my case, I had to fix the '<td>' padding.

**Comment by T00rk** [comment]
It's not that simple.
You probably don't use the timepicker :smile: ...

**Comment by T00rk** [comment]
I've just released the v 2.0.0. I've stopped using modal elements from Bootstrap Material Design and designed a new custom one. I've tried using it on my Galaxy SII and it works fine.

**Comment by shashvattrip** [comment]
So is it responsive now?
