### ISSUE TITLE
mindate option not locking previous year

### ISSUE THREAD

**Issue by nogdacosta** [T00rk/bootstrap-material-datetimepicker#16]
As you can see in the following image, if we're using the **mindate** option, we are still able to go to the previous year.

![datepicker_bug](https://cloud.githubusercontent.com/assets/4239608/8433677/2f914b54-1f3f-11e5-8dcf-5c1c0c363931.png)

It's happening because when checking if it's after the mindate, we show or hide the button for the month and the year at the same moment.

```JavaScript
if(!this.isAfterMinDate(startOfMonth, false, false))
{
    this.$dtpElement.find('a.dtp-select-month-before').addClass('hidden');
    this.$dtpElement.find('a.dtp-select-year-before').addClass('hidden');
}
else
{
    this.$dtpElement.find('a.dtp-select-month-before').removeClass('hidden');
    this.$dtpElement.find('a.dtp-select-year-before').removeClass('hidden');
}
```

**Comment by T00rk** [comment]
It's fixed. Can you confirm it works fine for you ?
Thank you

**Comment by nogdacosta** [comment]
Nice. it's working.

But noticed that if the mindate is set for the first day of one month, we can go to the previous month (despite none of the day is available for selection)
