### ISSUE TITLE
Moment is not defined

### ISSUE THREAD

**Issue by ShiftyMcCool** [T00rk/bootstrap-material-datetimepicker#169]
Hello,

I've got an issue that I can't seem to find any answer for online.  I'm using the datetimepicker with backbone and requirejs and when I load a page that uses this picker I get a moment error:
Uncaught ReferenceError: moment is not defined
    at bootstrap-material-datetimepicker.js?2017.05.26:1191

I have moment in the required paths and shimmed properly (hopefully).  This is my main file:
```
require.config({
	paths: {
		backbone: 	'libs/backbone-1.3.3.min',
		jquery: 	'libs/jquery-3.2.1.min',
		underscore: 'libs/underscore-1.8.3.min',
		bootstrap:	'libs/bootstrap.min',
		material:	'libs/material.min',
		ripples:	'libs/ripples.min',
		moment:		'libs/moment-with-locales.min',
		datepicker:	'libs/bootstrap-material-datetimepicker',
		validate: 	'libs/jquery.validate.min',
		cryptojs:	'libs/crypto-js.min',
		logger: 	'libs/logger',
		templates: 	'../templates'
	},
	shim: {
		moment: {
			exports: 'moment'
		},
		backbone: {
			deps: ['underscore', 'jquery'],
			exports: 'Backbone'
		},
		bootstrap: {
			deps: ['jquery'],
			exports: 'jquery'
		},
		ripples : {
			deps: ['jquery']
		},
		material: {
			deps: ['bootstrap', 'ripples']
		},
		validate: {
			deps: ['jquery']
		},
		datepicker: {
			deps: ['jquery', 'moment']
		}
	}
});
```
The page throwing the error begins like this.  No code has been run when the error appears... it comes up even before the backbone initialize function runs.  Adding ```console.log(moment().format('dddd, MMMM Do YYYY, h:mm:ss a'));``` to the initialize function works as expected:
```
define([
	'backbone',
	'moment',
	'datepicker',
	'text!templates/reports/repairFacilityReport.html'
], function(Backbone, moment, datepicker, repairFacilityReportTemplate) {
```
I'm pretty new at backbone and requirejs so I'm sure it's something I'm doing wrong, but I don't know what it is.  I haven't been able to find an example of this happening where it wasn't just an script include order issue (moment before datetimepicker, etc...)

Let me know if you need any other details.

Thanks in advance!

**Comment by renofizaldy** [comment]
i have same issue here, do you already found the answer?

**Comment by ShiftyMcCool** [comment]
Sorry, I stopped paying attention to this project since it was so clearly abandoned and we have moved away from Bootstrap completely.
