### ISSUE TITLE
MonthPicker Problem

### ISSUE THREAD

**Issue by hrshadhin** [T00rk/bootstrap-material-datetimepicker#175]
Month picker not working. here  is my code like this
`$('.datepicker3').bootstrapMaterialDatePicker({
        format: 'YYYY-MM',
        time:false,
        monthPicker:true,
    });`

**Comment by Dihgg** [comment]
Not work for me too.

The monthpicker seems to work
![image](https://user-images.githubusercontent.com/5893636/29368318-c3397750-8275-11e7-8eae-03486439ddef.png)
until you click on the `prev`
![image](https://user-images.githubusercontent.com/5893636/29368390-f4ac8070-8275-11e7-9325-126bd9d15fb9.png)

**Comment by mssc89** [comment]
I've fixed the problem, just paste
```
if (this.params.monthPicker === true)
{
     this._hideCalendar();
}
```

To the end of these functions

```
onMonthBeforeClick
onMonthAfterClick
onYearBeforeClick
onYearAfterClick
onYearRangeBeforeClick
onYearRangeAfterClick
```

I'm thinking about commiting this fix

**Comment by hrshadhin** [comment]
thanks. my is solved.

**Comment by Radhakrishanan** [comment]
@mssc89  am not having _hideCalendar() function in bootstrap-material-datetimepicker.js, could you give that function code...

**Comment by v1shva** [comment]
Why this issue is still not fixed?
