### ISSUE TITLE
 How can I close dialog by tab key

### ISSUE THREAD

**Issue by u2010** [T00rk/bootstrap-material-datetimepicker#194]
When multiple inputs are arranged like this sample
http://t00rk.github.io/bootstrap-material-datetimepicker/

1. press tab key and focus 
2. show datepicker dialog
3. press tab key and next focus
4. dialogs overlap open

I want to close the previous dialog before opening the next dialog.

**Comment by hugosoltys** [comment]
Up. This should be a natural behavior. 

I coded a workaround meanwhile.

`$(document).keyup(function (e) {
  if (e.keyCode === 9) {
    var currentDatePicker = $('.dtp:not(.hidden)');
    $('.dtp').addClass('hidden');
    if (!$(':focus').is('input')) {
      currentDatePicker.removeClass('hidden');
    }
  }
});
`

**Comment by u2010** [comment]
thanks you.
