### ISSUE TITLE
About date range picker

### ISSUE THREAD

**Issue by navinova** [T00rk/bootstrap-material-datetimepicker#21]
Thanks for this awesome job,

Any development about date range picker? 

Thanks

**Comment by T00rk** [comment]
Hi. What do you mean about date range picker ?
It's already possible to set a range between a minDate and a maxDate.

**Comment by navinova** [comment]
http://www.daterangepicker.com/#examples  Demo1,

I think your solution is better than this one. So maybe you can combine it.

**Comment by T00rk** [comment]
I won't do it.
It's now possible to have the same behavior.

You can do it this way

    <input type="text" id="date-begin" />
    <input type="text" id="date-end" />

    <script type="text/javascript">
        $(document).ready(function()
        {
            $('#date-end').bootstrapMaterialDatePicker({ format: 'DD/MM/YYYY HH:mm' });

            $('#date-begin').bootstrapMaterialDatePicker({ format: 'DD/MM/YYYY HH:mm' });            
            $('#date-begin').on('dateSelected', function(e, date)
            {
                $('#date-end').bootstrapMaterialDatePicker('setMinDate', date);
            });
        });
    </script>

**Comment by navinova** [comment]
Thanks. Looks like the same, but logic is different. 
Really thank you for your answers and this wonderful solution. 

Have a good day
