### ISSUE TITLE
Using with Meteor

### ISSUE THREAD

**Issue by reel** [T00rk/bootstrap-material-datetimepicker#22]
I am trying to use it with Meteor (i don't use the package).

I have a meteor project, with Materialize. I added the css and js file (in client/compatibility).

I binded the click event:

    <label for="eta" class="col-lg-3 control-label">E.T.A.</label>
    <input type="text" class="datepicker" name="eta" data-date-format="YYYY/MM/DD HH:mm" />

And the related JS:

    Template.addShip.events({
        'click .datepicker': function () {
            $('.datepicker').bootstrapMaterialDatePicker();
        }
    });

And the output is as the image attached.
![bootstrap-date-picker](https://cloud.githubusercontent.com/assets/766170/9040814/8650b94a-39d2-11e5-907f-044027cb2b0b.png)

**Comment by T00rk** [comment]
Is there some error in your console ?

**Comment by reel** [comment]
Nothing

**Comment by T00rk** [comment]
Can you add a breakpoint in the _onClick function and telle me whats happens ?

**Comment by seanjb** [comment]
Just had the same issue. It happens if you are not using the bootstrap. Which provides the .hidden class.

If you are using nemo64 bootstrap
then set the module 
"utilities"            : true

and it will fix it. Otherwise just add the CSS:
.hidden {
    display: none!important;
    visibility: hidden!important;
}
