### ISSUE TITLE
Use of rem units in CSS can cause display problems

### ISSUE THREAD

**Issue by beeb** [T00rk/bootstrap-material-datetimepicker#26]
The use of the `rem` units in the CSS causes the design to be messy if the root `font-size` (of the `html` tag styling) is not 10px.

**Comment by SvenSchoene** [comment]
Same issue here. Even setting the root-font-size to 10px somehow produces weird results for the date- and timepicker.

**Comment by beeb** [comment]
May I add that `line-height`s are inconsistent as well sometimes? Or should I open another issue?

**Comment by T00rk** [comment]
I know there is a problem with the timepicker when default values are changed.
I don't think it comes from `rem` units. The position of every minute is calculated in the js file but I don't  find values which works fine with every values.
Maybe I would need some help ...

**Comment by T00rk** [comment]
@beeb what do you mean by incosistent line-height ? 
Sometimes I need to set them higher than the font-size to set the correct alignement.

**Comment by beeb** [comment]
@T00rk regarding `rem` units, they relate to the root `font-size` (that of the `html` tag usually). This means that some dimensions in your CSS are linked to the user stylesheet and may vary from one user to the other. In my case, since my root `font-size` was 14px, every dimension expressed in `rem` was too big. I didn't test the time picker, only the date picker.
For the line-height, I noticed that not all of the elements have a defined `line-height` in your CSS, meaning that some elements of the date-time-picker can inherit wrong values for this property.

**Comment by Ugoku** [comment]
+1
The font size of of the date picker is much too large if the root font size is not 10px. Time picker seems fine

**Comment by T00rk** [comment]
Fixed in last release
