### ISSUE TITLE
Minutes Select

### ISSUE THREAD

**Issue by yashilanka** [T00rk/bootstrap-material-datetimepicker#27]
Hi i want to select 10:32pm time but there is no way to select that time because this is only select 5,10,15 ... so on, so how to select that time

**Comment by T00rk** [comment]
Sorry but I think I won't fix this. 
I made this plugin for a 5 minutes range selection.
I don't know how it could be possible to add avery minutes in a so small clock.
The aim is to have a clock working on mobile devices with small buttons to fit the size but big enough to be selected with finger. If I add 48 buttons I'm pretty sure it won't work.
You could propably cutomize it to add another selection view after minute selection with just four minutes before and four minutes after.
