### ISSUE TITLE
how have got to load moment-jalaali.js with bootstrap-material-datetimepicker.js

### ISSUE THREAD

**Issue by aliwsd** [T00rk/bootstrap-material-datetimepicker#30]
I Saw It, But My Question is how have got to load ```moment-jalaali.js``` with ```bootstrap-material-datetimepicker.js``` 
your plugin is working with momentjs.com and the ``` moment-jalaali.js ``` adds Jalaali calendar support to momentjs.com library.

**Comment by T00rk** [comment]
I've tried debugging with moment-jalaali plugin.
There is a bug on line 705. The string var is equal to 0 and the rest of the code is stopping.
What I wanted to explain in my last answer is I don't think it depends on me.
Maybe you could open an issue in the moment-jalaali repository.

**Comment by aliwsd** [comment]
ok thanks alot
