### ISSUE TITLE
Angular version of this plugin

### ISSUE THREAD

**Issue by ManiAkasapu** [T00rk/bootstrap-material-datetimepicker#31]
This is more like feature request. Can we expect Angular version of this plugin.
This is a great plugin. It would be very helpful if it supports angular.

Thankyou

**Comment by GabiAxel** [comment]
There is this project https://github.com/SimeonC/sc-date-time

**Comment by logbon72** [comment]
Check out my adaptation of this project for Angular Material 

http://logbon72.github.io/angular-material-datetimepicker/#
