### ISSUE TITLE
Multiple Month?

### ISSUE THREAD

**Issue by cepa1988** [T00rk/bootstrap-material-datetimepicker#36]
Is posible use multiple months? like Jquery Datepicker?

**Comment by T00rk** [comment]
What do you mean by multiple months ?

**Comment by jungti1234** [comment]
https://jqueryui.com/resources/demos/datepicker/multiple-calendars.html

you can see

**Comment by T00rk** [comment]
No I won't do it. 
You coul already navigate between months using arrows.
