### ISSUE TITLE
Usage with Rails 4

### ISSUE THREAD

**Issue by sahilbabbar** [T00rk/bootstrap-material-datetimepicker#42]
Hi,

I am using bootstrap material design with Rails 4 and trying to integrate this datepicker also, without success. I have included both css and js files in the assets directory and also included in their respective application files, but it is not working. It is giving a console error: 
`Uncaught TypeError: $(...).bootstrapMaterialDatePicker is not a function`

**Comment by mathroc** [comment]
looks like bootstrap-material-datetimepicker.js is not loaded make sure it's included and that jquery is not included after it
