### ISSUE TITLE
Problem with "Google Material Icon Font" for offline?

### ISSUE THREAD

**Issue by thearabbit** [T00rk/bootstrap-material-datetimepicker#45]
I use this package on `Meteor JS`.
But I have problem with `Google Material Icon Font` for offline.
Please help me (How to add to offline?).

**Comment by electricfan** [comment]
they now switch to material google font, you can take a look here https://design.google.com/icons/#ic_subject, it has an offline version where you can use for your local purpose.

**Comment by thearabbit** [comment]
Thanks for your reply.
