### ISSUE TITLE
Selecting minute hand non-intuitive

### ISSUE THREAD

**Issue by mintuhouse** [T00rk/bootstrap-material-datetimepicker#47]
I was playing around with demo page for a while to include it in one of my projects. 
The minute selection part of timepicker was not very intuitive atleast for me. I  tried in vain to double click, drag on minutes hand to select the minutes. (Finally a colleague of mine figured it out)

Can you make it similar to default android behaviour, 
1. where only minute hand is invisible while selecting the hour hand and vice-versa
2. And also instead of clicking ok to switch between hour and minute hand, auto switch to minutes hand once hour is selected.

**Comment by pos1tron** [comment]
I'm sitting here trying to get it work with no luck. How exactly do you use the minute hand?

**Comment by mintuhouse** [comment]
Click on OK button below

**Comment by pos1tron** [comment]
Of course! I was assuming I was expected to interact with the minute hand before clicking OK.

**Comment by T00rk** [comment]
@pos1tron You can set **switchOnClick** to true if you want view to change without clicking "ok" button

**Comment by pos1tron** [comment]
Thanks! And thanks for your hard work making this repo a reality, it's a
great tool.

On Thu, Feb 11, 2016 at 5:40 PM, T00rk <notifications@github.com> wrote:

> @pos1tron <https://github.com/pos1tron> You can set *switchOnClick* to
> true if you want view to change without clicking "ok" button
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/T00rk/bootstrap-material-datetimepicker/issues/47#issuecomment-183088417>
> .
>



--

**Comment by mintuhouse** [comment]
Thank you for the config option
