### ISSUE TITLE
display all minutes,  not by 5

### ISSUE THREAD

**Issue by electricfan** [T00rk/bootstrap-material-datetimepicker#49]
is there a way I could render the whole minutes like 1 - 60 and not per 5 mins, currently the set up of minutes are (5, 10, 15, 20, 25, 30 .. etc), I want like (1, 2, 3, 4, 5 ..etc) any ideas how to do make it like that please? anyway, Good job! I really love your material datetimepicker.

**Comment by j0ssGZ** [comment]
Change line 415:
for(var m = 0; m < 60; m += 5)
to
 for(var m = 0; m < 60; m += 1)

But I don't recommend this becouse the div haven't enought space for all minutes and the view crash.

See u!

**Comment by T00rk** [comment]
Every minutes are selectable. 
Only the multiples of 5 have text but you can select the minutes which are between.
On the next release i'll implement hand dragging.

**Comment by me-cedric** [comment]
Any news on hows the dragging is going ? Selecting minutes which are bettween 5 isn't really intuitive, nor really optimized. I 'd love to see this feature implemented, would be a great addon to this project !

Also could it be possible to display every minutes, but the ones not beeing multiple of 5 would be smaller so it fits ?

Thank you for the great work !
