### ISSUE TITLE
Timepicker returns as a date

### ISSUE THREAD

**Issue by pradt** [T00rk/bootstrap-material-datetimepicker#50]
Hi I'm using the datetimepicker on a field just for as a time picker. So I'm initialising it like the demo $(".timepicker").bootstrapMaterialDatePicker({ date: false }); the plugin is appearing and I can select the time from the timepicker, but the text field shows a date.

Is there anything else that i need to do to get the time ?

**Comment by Ugoku** [comment]
I had this problem too, try adding `format: 'HH:mm'` in your time picker options like this:
```
jQuery('.input-time').bootstrapMaterialDatePicker({
            date: false,
            format: 'HH:mm',
        });
```
This fixed it for me.

**Comment by SekharBeri** [comment]
I had a different problem. i have added date: false as an option. Still it showing calendar instead of time picker
