### ISSUE TITLE
Fails on changing language

### ISSUE THREAD

**Issue by demipel8** [T00rk/bootstrap-material-datetimepicker#51]
Hi, I'm working on a multilanguage panel with angular.

I have a problem when trying to edit a date that is in a languaje different than english.

![invaliddate](https://cloud.githubusercontent.com/assets/4971724/12320027/7482ffd4-baa6-11e5-8ccb-29da3222a090.png)

I have been able to fix it by adding ```moment.locale(this.params.lang);``` at the Plugin function before ```this.init()``` but, is there a way to do it without modifying the plugin?

**Comment by giolvani** [comment]
I saw that weird thing also. I think you should do a pull request.
