### ISSUE TITLE
24 hour support

### ISSUE THREAD

**Issue by Ugoku** [T00rk/bootstrap-material-datetimepicker#54]
Android (5.1) shows the following time selection when using a 24 hour clock (i.e. a *lot* of countries):
![timepicker](https://cloud.githubusercontent.com/assets/3470653/12478067/3f1a2e16-c033-11e5-9c16-b61f97d07795.png)
Can you please add this to your time picker? AM/PM is not intuitive to users in my country.

**Comment by CoalaJoe** [comment]
+1 for usability

**Comment by T00rk** [comment]
Fixed in new release

**Comment by Ugoku** [comment]
Finally had a chance to look at this, thanks for adding!
