### ISSUE TITLE
On popup modal shows "cancel" but not "ok"

### ISSUE THREAD

**Issue by Poolaidman** [T00rk/bootstrap-material-datetimepicker#56]
This is a really nice addition of date picker. I have tested in mac chrome,safari & ios 9 and I am missing the ok button. It is really there just below the modal,unseen on the phone. 
![screenshot 2016-02-02 22 02 44](https://cloud.githubusercontent.com/assets/7898445/12774401/589ce854-c9f9-11e5-879a-a5f48e900fc6.png)

I have changed css to display:none the cancel button for now as they can exit via the x button on top.. 
`.dtp-btn-cancel {
  display: none !important;
}`

and now I get 
![screenshot 2016-02-02 22 09 37](https://cloud.githubusercontent.com/assets/7898445/12774435/b6bd5e8c-c9f9-11e5-8666-fa95efbe3a4c.png)

I am using material-bootstrap via
http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

Also I have loaded 

<link rel="stylesheet" type="text/css" href="selectize.js-master/dist/css/selectize.css" />
<link rel="stylesheet" type="text/css" href="material-datetimepicker/css/bootstrap-material-datetimepicker.css" />
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="moment-js/min/moment-with-locales.min.js" charset="utf-8"></script>
<script src="material-datetimepicker/js/bootstrap-material-datetimepicker.js" charset="utf-8"></script>

Thanks for the product again, this thing looks great

**Comment by T00rk** [comment]
The problem is fixed.
Can you confirm it works fine ? 
Thank you

**Comment by Poolaidman** [comment]
I changed out the old version for the new and removed my css none display block and still got the same result

![screenshot 2016-02-04 14 48 36](https://cloud.githubusercontent.com/assets/7898445/12832405/9e2a61c0-cb4e-11e5-88e9-b7b5751880ce.png)
