### ISSUE TITLE
Rendering buttons below modal

### ISSUE THREAD

**Issue by igorlovric** [T00rk/bootstrap-material-datetimepicker#57]
I'm using datetime picker together with bootstrap material design (https://github.com/FezVrasta/bootstrap-material-design)

If I set clearButton and nowButton options to true, Cancel and OK buttons are rendered below modal.

![2016-02-03 22_53_41-store](https://cloud.githubusercontent.com/assets/11973815/12798395/745b0730-cac9-11e5-9cf3-82dcf4f22dd0.png)

I solve it by adding fallowing lines of code:

if ((this.params.nowButton === true) && (this.params.clearButton === true)) {
     this.$dtpElement.find('.dtp-btn-clear, .dtp-btn-now, .dtp-btn-cancel, .dtp-btn-ok').addClass('btn-xs');
} else if ((this.params.nowButton === true) || (this.params.clearButton === true)) {
     this.$dtpElement.find('.dtp-btn-clear, .dtp-btn-now, .dtp-btn-cancel, .dtp-btn-ok').addClass('btn-sm');
}

on the end on initButtons function.

This is how it looks fixed (displaying four buttons): 

![2016-02-03 22_54_39-store](https://cloud.githubusercontent.com/assets/11973815/12798456/d4073514-cac9-11e5-91c8-888c587a84b4.png)

Or like this with three buttons:

![2016-02-03 23_02_12-store](https://cloud.githubusercontent.com/assets/11973815/12798558/64a67fd0-caca-11e5-83c2-ff18c313296c.png)

It would be nice if you could implement something like this in original code, or just add option to set additional buttons class manualy. eg: btnClass: "btn-xs"

**Comment by T00rk** [comment]
I've fixed the problem using your code.
Thank you
