### ISSUE TITLE
Show date picker programmatically

### ISSUE THREAD

**Issue by betoxx** [T00rk/bootstrap-material-datetimepicker#61]
Show date picker programmatically ex: $('#date').bootstrapmaterial('show')

**Comment by pos1tron** [comment]
Here's how I do it:
```javascript
// initialize and gain reference to the date picker instance
var picker = $('yourSelector')
    .bootstrapMaterialDatePicker(yourOptions)
    .data('plugin_bootstrapMaterialDatePicker');

// this opens the date picker
picker._onClick();
```

**Comment by betoxx** [comment]
Perfect! But the function is _onFocus

`// initialize and gain reference to the date picker instance
var picker = $('yourSelector')
    .bootstrapMaterialDatePicker(yourOptions)
    .data('plugin_bootstrapMaterialDatePicker');

// this opens the date picker
picker._onFocus();`

**Comment by pos1tron** [comment]
Ah yeah, looks like i'm still running an older version. Thanks for the follow up.
