### ISSUE TITLE
Question: Is it possible to inline the picker?

### ISSUE THREAD

**Issue by mintuhouse** [T00rk/bootstrap-material-datetimepicker#78]
Similar to 
http://eonasdan.github.io/bootstrap-datetimepicker/#inline

**Comment by T00rk** [comment]
I think it's possible with a different css file.
I considere CSS as sorcery (sometimes it works, and sometimes it doesn't without knowing why), so I don't want to have to deal with it more than needed.

If someone wants to create a PR i'll merge it with pleasure but that won't be me. Sorry.

**Comment by mintuhouse** [comment]
Thanks @T00rk for the quick reply. Will use the other picker for now in that case.
