### ISSUE TITLE
Jalali calendar 

### ISSUE THREAD

**Issue by manisi** [T00rk/bootstrap-material-datetimepicker#80]
Hi,
Jalali calendar ?
thanks

**Comment by T00rk** [comment]
Add this dependency 
https://github.com/jalaali/moment-jalaali

**Comment by atiyehahmadi** [comment]
![download](https://user-images.githubusercontent.com/33490348/106037109-76b3ad80-60eb-11eb-94d2-ed90d5eca65f.png)

Hi, I added the moment-jalaali and its dependencies like (
 moment.locale('fa');
  moment.loadPersian();
and extra) an I change the date base on jalali format (format: 'jYYYY-jMM-jDD') and now the days on bottom vs top are completely different. 

Can you give me a hint or help?
