### ISSUE TITLE
Bower version conflict

### ISSUE THREAD

**Issue by RohanSakhale** [T00rk/bootstrap-material-datetimepicker#81]
Currently the dependencies are resolving to a lower version

## Libraries

 - jQuery - `1.11.0` which is quite fixed
 - momentjs - `~2.10.2` 
 - bootstrap-material-design - `~0.3.0`

Can this be updated to the latest versions, as it will help everything remain updated

**Comment by 719media** [comment]
+1, at the very least could you use ">=1.11.0" or equivalent so with higher versions we don't get errors.

**Comment by T00rk** [comment]
Fixed
