### ISSUE TITLE
Closure compiler error

### ISSUE THREAD

**Issue by BenjaminBehringer** [T00rk/bootstrap-material-datetimepicker#83]
Hi,

I used closure compiler to make the JS smaller for deployment. Unfortunately I ran into this error:

    JSC_PARSE_ERROR: Parse error. Invalid delete operand. Only properties can be deleted. at line 47 character 0
					delete $.data(this, pluginDataName);

Any thoughts on this problem? Can we get around the error somehow?

Regards,
Benjamin

**Comment by T00rk** [comment]
Hi,
Maybe you can replace `delete $.data(this, pluginDataName)` by `$.removeData(this)`

**Comment by BenjaminBehringer** [comment]
Yes, that works. Why don't you use that solution at the moment? Can we switch to your proposal safely?

**Comment by T00rk** [comment]
I didn't thought about it.
I will pull it in the next release.

This is safe. It's a Jquery native way to delete data.

**Comment by BenjaminBehringer** [comment]
Thank you!

**Comment by ValentinVoigt** [comment]
It seems like the problem still exists. Could you please fix this?

**Comment by Inzlinger** [comment]
bump.
