### ISSUE TITLE
allow only to select from current day, month, year and on wards

### ISSUE THREAD

**Issue by electricfan** [T00rk/bootstrap-material-datetimepicker#86]
Hi, how can I allow only to select from current day, month, year and onwards ?(must not allow to select previous day, month and year), any help, clues, ideas please?

**Comment by T00rk** [comment]
You can set MinDate and MaxDate

**Comment by electricfan** [comment]
Thank you for the fast response, I tried this

`$('.datepicker').bootstrapMaterialDatePicker({ weekStart : 0, time: false, format : 'MMMM DD, YYYY',setMinDate : moment().format('MMMM DD, YYYY') });`

but unfortunately, I could still able to select the previous date, any help, ideas, clues please?

**Comment by electricfan** [comment]
thank you its working now! :)
