### ISSUE TITLE
Weird time picker get the date instead???

### ISSUE THREAD

**Issue by nickgoodrow** [T00rk/bootstrap-material-datetimepicker#89]
I am using:
 $('#time').bootstrapMaterialDatePicker({ date: false, time: true });

I got the time picker poping up... but the input field get filled with a date ?!?!?!

I tried a work around with JS and the DOM... it works but...

var timePicked = $('.dtp-time > .dtp-actual-maxtime');
       
        $('.dtp-buttons > .dtp-btn-ok').click(function () {
            alert('timePicked.text(): ' + timePicked.text().substr(5)); // will assign to #time element
           
        });

Frustrating... any idea why I have an issue in the first place?

**Comment by electricfan** [comment]
can you provide a screenshot of what it looks like?

**Comment by T00rk** [comment]
$('#time').bootstrapMaterialDatePicker({ date: false, time: true, **format: 'HH:mm'** });

**Comment by nickgoodrow** [comment]
DOh! Thanks. Works like a charm
