### ISSUE TITLE
Can't view hour and minute in a clock on Internet Explorer

### ISSUE THREAD

**Issue by Orpheusz** [T00rk/bootstrap-material-datetimepicker#92]
Hi,
I can't view the hours and minutes on a clock when this running on IE, the frame dimension change and become smaller than date selection, in the other browser I view all perfectly.
I use all version of Explorer (edge,11,10 etc..) but the result is the same...
Please help me to fix this problem :)

**Comment by T00rk** [comment]
Can you post a screenshot please ?

**Comment by Orpheusz** [comment]
Yes sorry :) 
![clock](https://cloud.githubusercontent.com/assets/18346307/14380075/fd439d14-fd7d-11e5-8c46-6db7b68352ba.JPG)

**Comment by T00rk** [comment]
You can find everything here
https://github.com/T00rk/bootstrap-material-datetimepicker/issues/85

**Comment by Orpheusz** [comment]
Ok, it's worked for me! 
Thanks a lot :)
