### ISSUE TITLE
update tags to the latest version

### ISSUE THREAD

**Issue by maruilian11** [T00rk/bootstrap-material-datetimepicker#94]
hi, recently we want to add your lib on https://cdnjs.com, could you please update the git tag to the latest version so that we can use **git auto-update  config** to update the lib.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/7546

**Comment by T00rk** [comment]
I created a release for 2.7.1 version.
Is that ok ?

**Comment by maruilian11** [comment]
yes, thank you! if you can add tag after releasing we'll be grateful.
