### ISSUE TITLE
Its possible Disable Specific days of week?

### ISSUE THREAD

**Issue by bonzinho** [T00rk/bootstrap-material-datetimepicker#97]
Hi, 

its not possible Disable Specific days of week?

thanks

**Comment by T00rk** [comment]
Not for the moment but I've planned to add it

**Comment by T00rk** [comment]
#60

**Comment by aljohnreyvirtudazo** [comment]
Hi

@T00rk @donovansolms  can you help me disable specific hours in timepicker i.e, night hours from 10pm onwards?

Thank you
